// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjMW3ZN4of9kJH-NquATH8pXPxI_gpoeY',
    appId: '1:128130442746:web:ba9ea8f5e98e243a953043',
    messagingSenderId: '128130442746',
    projectId: 'triptide-9f798',
    authDomain: 'triptide-9f798.firebaseapp.com',
    storageBucket: 'triptide-9f798.firebasestorage.app',
    measurementId: 'G-NG1YTEC3PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn3G7TytaDEXT96jHbwwmODL5HrGQkG9w',
    appId: '1:128130442746:android:332a2de901a1e5dc953043',
    messagingSenderId: '128130442746',
    projectId: 'triptide-9f798',
    storageBucket: 'triptide-9f798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiO_O1O19mFWbJBV0T7zP3AaFAYZ1eT1M',
    appId: '1:128130442746:ios:2d38fdfd1ce4bfab953043',
    messagingSenderId: '128130442746',
    projectId: 'triptide-9f798',
    storageBucket: 'triptide-9f798.firebasestorage.app',
    iosBundleId: 'com.example.triptide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiO_O1O19mFWbJBV0T7zP3AaFAYZ1eT1M',
    appId: '1:128130442746:ios:2d38fdfd1ce4bfab953043',
    messagingSenderId: '128130442746',
    projectId: 'triptide-9f798',
    storageBucket: 'triptide-9f798.firebasestorage.app',
    iosBundleId: 'com.example.triptide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjMW3ZN4of9kJH-NquATH8pXPxI_gpoeY',
    appId: '1:128130442746:web:d83d53935b532894953043',
    messagingSenderId: '128130442746',
    projectId: 'triptide-9f798',
    authDomain: 'triptide-9f798.firebaseapp.com',
    storageBucket: 'triptide-9f798.firebasestorage.app',
    measurementId: 'G-E46MTN45CW',
  );
}
